In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv('../input/home-prices/homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[["area"]],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [6]:
model.predict([[5000]])

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

Save Model to file using pickle

In [7]:
import pickle

In [8]:
with open("model_from_pickle",'wb') as file:
    pickle.dump(model,file)

In [9]:
 #loading saved model
with open("model_from_pickle",'rb') as file:
    mp = pickle.load(file)

In [10]:
mp.predict([[5000]])

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

Save trained model using joblib

In [11]:
from joblib import load,dump

In [12]:
dump(model,'model_from_joblib')

['model_from_joblib']

In [13]:
mj = load('model_from_joblib')

In [14]:
mj.predict([[5000]])

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])